spring.application.name=jirapobre
spring.datasource.url=jdbc:postgresql://localhost:5432/seguridad
spring.datasource.username=postgres
spring.datasource.password=134340
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
server.port=8081