spring.application.name=jirapobre
spring.datasource.url=jdbc:postgresql://localhost:5432/seguridad
spring.datasource.username=postgres
spring.datasource.password=134340
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
server.port=8081
jwt.secret=ec6127bb4ee33ef91a86802d00ec2574f324daab8866d1e1758a0a251743fd3face815f92822ff62ec722880fc9091f6240d047786aabc15d633502c69d2c49c
jwt.expiration=86400000
springdoc.api-docs.enabled=true
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.enabled=false